require: rubocop-jekyll

inherit_gem:
  rubocop-jekyll: .rubocop.yml

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
      - vendor/**/*

Jekyll/NoPutsAllowed:
  Enabled: false

Metrics/LineLength:
  Max: 154

Metrics/MethodLength:
  Max: 40

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
